### ISSUE TITLE
Explore / Integrate currency and inflation data into "Economics"

### ISSUE THREAD

**Issue by skipjack** [project-seldon/intake#28]
This type of data seems like a logical next step for our "Economics" summary, though probably more interesting in some sort of historical "Explore" view. I'll try to flesh out the idea a little more in Figma but ideas are welcome...

- [x] Identify different international sources (e.g. world bank, imf, etc) for this type of data.
- [x] Spec out / design what we want for the worldwide and country level visualizations.
- [x] Choose from the sources we've identified.
- [x] Write the scraper.

**Comment by JeydenP** [comment]
Here are a few quick links from sources we already use and google:

https://data.worldbank.org/indicator/FP.CPI.TOTL.ZG?end=2021&start=2021&view=map
https://www.imf.org/external/datamapper/PCPIPCH@WEO/OEMDC
https://data.oecd.org/price/inflation-cpi.htm#indicator-chart
(For this site, it shows CPI, which we already have, but I noticed it also shows housing prices)

https://data.bls.gov/cgi-bin/cpicalc.pl?cost1=1%2C000.00&year1=191301&year2=202212
(I don't know; I think this calculator is cool) - off track

**Comment by skipjack** [comment]
Our conclusion from Sunday was...

- We should grab the CPI data from IMF rather than world bank (because it goes past 2023.
- We should explore other metrics like...
  - https://data.worldbank.org/indicator/FP.WPI.TOTL?end=2021&start=1960&view=chart
  - https://www.netsuite.com/portal/business-benchmark-brainyard/industries/articles/cfo-central/inflation-indicators.shtml
  - https://www.theglobaleconomy.com/rankings/mortgage_interest_rate/

**Comment by gerard070** [comment]
great potential source of data
https://fred.stlouisfed.org/docs/api/fred/

**Comment by skipjack** [comment]
Ok, so here's where we landed yesterday...

- We'll just add the new inflation metrics initially to the existing worldwide economics chart.
- These new metrics (+ the others we hadn't yet exposed on the worldwide page) will be made available in the dropdown.
- @JeydenP will own scraping the new metrics and I'll own integrating them into the chart.

We revisited the links above, did a bit more digging and decided that we'll aim to scrape historical data for the following metrics internationally...

- [x] Consumer Price Index (WorldBank and IMF)
- [x] Producer Price Index (OECD, maybe FRED or BLS)
- [x] Wholesale Price Index (WorldBank ~~and maybe Moody's~~)
- [x] Employment Cost Index (BLS, FRED) - Maybe get _OECD Unit Labor Cost_ instead?
- Mortgage Interest Rate (this one may be the toughest to find, deciding to ignore for now)

Down the road we may explore more specific visualizations for specific economic metrics (or groups of metrics) as well but that's out of scope here for now. The following types of charts seemed like potential options...

- https://geerthofstede.com/country-comparison-graphs/ (e.g. compare two related metrics)
- https://nivo.rocks/swarmplot/ (e.g. one metric and groups are regions of the world)
- https://nivo.rocks/sunburst/ (e.g. for metrics that add up to a world total, like world gdp => region gdp => country gdp)
- https://fred.stlouisfed.org/series/FPCPITOTLZGUSA (something like this would be further down the road once we have historical views across _multiple_ years)

The above would take more design work and thought, we'd have to pick design relevant version of those with our data and align them with our overall aesthetic which stems from [here][1] and [here][2].

[1]: https://dribbble.com/shots/10969130-Campaign-Report-UI-SET-01-1
[2]: https://dribbble.com/shots/11021864-Dashboard-View-SET-01-2

**Comment by skipjack** [comment]
For OECD Unit Labour Cost...

https://data.oecd.org/lprdty/unit-labour-costs.htm

I think we want to use the CSV format from their API again with whatever these settings end up being behind the scenes:

![image](https://user-images.githubusercontent.com/8988697/229956646-bcb83820-5803-4ee7-92f9-94e965e08209.png)
