### ISSUE TITLE
Render Issue on Explore Page

### ISSUE THREAD

**Issue by gerard070** [project-seldon/intake#29]
This is challenging to replicate but i was able to do so after about 2 minutes of "load testing" (abusing the year slider)

Yesterday I experience this bug as soon as i landed on the explore page and engaged the date slider. Today it took a few minutes to replicate the error. 

See attached video

https://user-images.githubusercontent.com/20401390/189544514-e3118cc9-1372-4a80-9621-01584779b0d1.mov

**Comment by skipjack** [comment]
Screen Recording: https://fsty.io/v/QLmR6ggd

**Comment by skipjack** [comment]
I think I have a fix for this queued up, just debugging one or two other issues in the new dataset.
