### ISSUE TITLE
Explore / Update "no data" messaging in summaries

### ISSUE THREAD

**Issue by gerard070** [project-seldon/intake#32]
Currently, when we don't have data for a statistic, we show "Unknown" which is not very helpful to the user. It would be better to update the copy to indicate we do not have data for that particular year, rather then that the entire field is "unknown"

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/20401390/214988319-4dfd753e-1d52-4b3c-a33b-7fe1d68a81cc.png">

**Comment by gerard070** [comment]
Instead of "unknown" we change the copy to "unavailable" and add a tool tip/info that allows our standard "nothing found" UI component

![image](https://user-images.githubusercontent.com/20401390/218320744-0d64ea9f-e58e-4ca5-8954-44208b6447a4.png)

**Comment by skipjack** [comment]
Let's just say these are the action items...

- [ ] Load up a more recent scrape (this will populate many of the unpopulated 2022 data points).
- [x] Update wording to "Unavailable" instead of "Unknown" and introduce a per metric tooltip with a similar callout to the "Nothing Found" one above.
