### ISSUE TITLE
Explore / Bug In US Representative Data for 1960 

### ISSUE THREAD

**Issue by gerard070** [project-seldon/intake#35]
<img width="1250" alt="image" src="https://user-images.githubusercontent.com/20401390/220803265-29240446-7489-4cf2-b7aa-229df22cb02b.png">
 
Something is not right our 1960 data for the US representatives.

**Comment by skipjack** [comment]
Here's the corresponding commit that fixed this, see the commit message for details on what was wrong...

project-seldon/research@8e8d53384549c7cd66d9038fdb8ffaea7ab99ad4
