### ISSUE TITLE
Explore / Politics / Politicians by sexual orientation breakdown

### ISSUE THREAD

**Issue by skipjack** [project-seldon/intake#41]
Similar to #40 (depending on the visualization it could even be done in the same place), and stemming from [another quora thread][1] in project-seldon/spec#23, we now have [a source][2] for US politician sexual orientation that we could pull from to enrich our data and subsequently visualize.

[1]: https://www.quora.com/What-proportion-of-US-legislators-is-openly-LGBT-In-the-UK-45-out-of-650-are
[2]: https://en.wikipedia.org/wiki/List_of_LGBT_members_of_the_United_States_Congress

**Comment by gerard070** [comment]
- Create new field in persons called sexual_orientiation
- Any users pulled from the data source will have a sexual_orientiation = LGBT, all others = Not LGBT
- Start in enrichOfficials but outside of for loop (to avoid pinging for each official)
- Leverage official.meta.wikipedia id to map new data points (getPersonWiki gives us an ID)
- pull source and add
