### ISSUE TITLE
Explore / Expose and grab from sources new stats objects

### ISSUE THREAD

**Issue by gerard070** [project-seldon/intake#42]
Stubbing ticket for now @skipjack  per our discovery that the senate source is missing from the UI

<img width="1208" alt="image" src="https://github.com/project-seldon/intake/assets/20401390/955e92ee-fe18-4cea-a27a-1d079ae170d4">

**Comment by skipjack** [comment]
Ok, deep in this now. I have `sources` exposed on all our new `statistics` objects but this section isn't pulling from there yet (it's pulling directly from `roles`).

That being said, it would be a nice optimization to have dedicated statistics for these seating charts so I'm just going to do that now and expose sourcing on them as well. Then will update the UI to read from the new location.
