### ISSUE TITLE
Learn / Add blog section and first blog post

### ISSUE THREAD

**Issue by gerard070** [project-seldon/intake#43]
While we continue to add more countries to our datasets, we will need to do the preliminary research of understanding their governmental structure and its specific nuances. Doing so will enable us to integrate country level data into our existing indices and data sets more thoughtfully, and set the stage for what data we pull and what sources we pull it from.

Since we need to do the research anyways, we might as well write it down for others to consume and if we optimize the generated build (SEO) for the "Learn" section of our site then we get these value adds...

### For Users

- Providing a high level textual description of the underlying data to follow
- Centralizing these types of comparisons on our site
- Giving them a head start into the "Explore" and "Learn" sections of our site

### For Project Seldon

- Provide high value insight for users
- Build the sites internet footprint, assisting in organic SEO
- Allow us to onboard less technical contributors to assist and add value to the site (i.e. Graduate Students)
- Enable more broad reaching outreach given the reduced specificity of the information we would have to share (not such a heavy drill down, but a higher level overview of a given governments structure).

**Comment by skipjack** [comment]
So I just learned Next.js for another project but I'd like to experiment with [vite][1] and [this plugin][2] for our use case. Reason being is the `vite` is faster, has a better dx in some other regards and couples us less to particular hosting platforms.

[1]: https://vitejs.dev/
[2]: https://vite-plugin-ssr.com/
