### ISSUE TITLE
Search / Voting history expansion only if necessary

### ISSUE THREAD

**Issue by skipjack** [project-seldon/intake#7]
Right now we show the expander chevron icon no matter how long the vote description is...

![image](https://user-images.githubusercontent.com/8988697/157062802-4a70be6b-4f52-4d05-9f9d-ecab1767428d.png)

This feels a little funny when clicking the arrow doesn't reveal anything. We should be able to use the following techniques to detect truncation and only show the arrow if truncated...

- https://stackoverflow.com/questions/7738117/html-text-overflow-ellipsis-detection
- https://stackoverflow.com/questions/52232026/determine-if-ellipsis-is-being-displayed-when-using-webkit-line-clamp-for-multi

**Comment by skipjack** [comment]
This would be made irrelevant if there were additional data points we always revealed for each vote but I'm not sure we have any worth showing at the moment.

**Comment by gerard070** [comment]
> This would be made irrelevant if there were additional data points we always revealed for each vote but I'm not sure we have any worth showing at the moment.

Some competitor sources if we did want to add more data points https://www.govtrack.us/about-our-data
